### ISSUE TITLE
uflo2-2.0.4版本跟springboot项目整合，部署成功，但启动流程报错

### ISSUE THREAD

**Issue by wsg215** [youseries/uflo#14]
启动报错日志如下：

2017-11-05 14:53:57.949 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/pxdzV-Uflo].[ufloServlet] Line:181 - Servlet.service() for servlet [ufloServlet] in context with path [/pxdzV-Uflo] threw exception [java.lang.reflect.InvocationTargetException] with root cause
java.lang.RuntimeException: 开始1 history activity node does not exist
	at com.bstek.uflo.command.impl.SaveHistoryActivityCommand.execute(SaveHistoryActivityCommand.java:72)
	at com.bstek.uflo.command.impl.SaveHistoryActivityCommand.execute(SaveHistoryActivityCommand.java:37)
	at com.bstek.uflo.command.impl.SpringTransactionCommandService$1.doInTransaction(SpringTransactionCommandService.java:53)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
	at com.bstek.uflo.command.impl.SpringTransactionCommandService.executeCommand(SpringTransactionCommandService.java:51)
	at com.bstek.uflo.process.node.Node.saveActivityHistory(Node.java:75)
	at com.bstek.uflo.process.node.Node.completeActivityHistory(Node.java:82)
	at com.bstek.uflo.process.flow.SequenceFlowImpl.execute(SequenceFlowImpl.java:57)
	at com.bstek.uflo.process.node.Node.leaveNode(Node.java:96)
	at com.bstek.uflo.process.node.StartNode.leave(StartNode.java:92)
	at com.bstek.uflo.command.impl.StartProcessInstanceCommand.execute(StartProcessInstanceCommand.java:85)
	at com.bstek.uflo.command.impl.StartProcessInstanceCommand.execute(StartProcessInstanceCommand.java:38)
	at com.bstek.uflo.command.impl.SpringTransactionCommandService$1.doInTransaction(SpringTransactionCommandService.java:53)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
	at com.bstek.uflo.command.impl.SpringTransactionCommandService.executeCommand(SpringTransactionCommandService.java:51)
	at com.bstek.uflo.service.impl.DefaultProcessService.startProcess(DefaultProcessService.java:162)
	at com.bstek.uflo.service.impl.DefaultProcessService.startProcessById(DefaultProcessService.java:138)
	at com.bstek.uflo.console.handler.impl.central.CentralServletHandler.startProcess(CentralServletHandler.java:189)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.bstek.uflo.console.handler.BaseServletHandler.invokeMethod(BaseServletHandler.java:36)
	at com.bstek.uflo.console.handler.impl.central.CentralServletHandler.execute(CentralServletHandler.java:69)
	at com.bstek.uflo.console.UfloServlet.service(UfloServlet.java:75)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.alibaba.druid.support.http.WebStatFilter.doFilter(WebStatFilter.java:123)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:105)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Unknown Source)
2017-11-05 14:53:57.949 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/pxdzV-Uflo].[ufloServlet] Line:181 - Servlet.service() for servlet [ufloServlet] in context with path [/pxdzV-Uflo] threw exception [java.lang.reflect.InvocationTargetException] with root cause
java.lang.RuntimeException: 开始1 history activity node does not exist
	at com.bstek.uflo.command.impl.SaveHistoryActivityCommand.execute(SaveHistoryActivityCommand.java:72)
	at com.bstek.uflo.command.impl.SaveHistoryActivityCommand.execute(SaveHistoryActivityCommand.java:37)
	at com.bstek.uflo.command.impl.SpringTransactionCommandService$1.doInTransaction(SpringTransactionCommandService.java:53)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
	at com.bstek.uflo.command.impl.SpringTransactionCommandService.executeCommand(SpringTransactionCommandService.java:51)
	at com.bstek.uflo.process.node.Node.saveActivityHistory(Node.java:75)
	at com.bstek.uflo.process.node.Node.completeActivityHistory(Node.java:82)
	at com.bstek.uflo.process.flow.SequenceFlowImpl.execute(SequenceFlowImpl.java:57)
	at com.bstek.uflo.process.node.Node.leaveNode(Node.java:96)
	at com.bstek.uflo.process.node.StartNode.leave(StartNode.java:92)
	at com.bstek.uflo.command.impl.StartProcessInstanceCommand.execute(StartProcessInstanceCommand.java:85)
	at com.bstek.uflo.command.impl.StartProcessInstanceCommand.execute(StartProcessInstanceCommand.java:38)
	at com.bstek.uflo.command.impl.SpringTransactionCommandService$1.doInTransaction(SpringTransactionCommandService.java:53)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
	at com.bstek.uflo.command.impl.SpringTransactionCommandService.executeCommand(SpringTransactionCommandService.java:51)
	at com.bstek.uflo.service.impl.DefaultProcessService.startProcess(DefaultProcessService.java:162)
	at com.bstek.uflo.service.impl.DefaultProcessService.startProcessById(DefaultProcessService.java:138)
	at com.bstek.uflo.console.handler.impl.central.CentralServletHandler.startProcess(CentralServletHandler.java:189)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.bstek.uflo.console.handler.BaseServletHandler.invokeMethod(BaseServletHandler.java:36)
	at com.bstek.uflo.console.handler.impl.central.CentralServletHandler.execute(CentralServletHandler.java:69)
	at com.bstek.uflo.console.UfloServlet.service(UfloServlet.java:75)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.alibaba.druid.support.http.WebStatFilter.doFilter(WebStatFilter.java:123)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:105)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Unknown Source)

**Comment by wsg215** [comment]
请教下，启动时，读取这张表【uflo_his_activity 】 ，正常流程部署成功之后，这张表应该有数据吗？这个好像是个历史表，刚部署成功之后也不应该有数据才对。

**Comment by youseries** [comment]
刚基于2.0.4测了下标准项目及springboot项目，都是好的，没出现你遇到的问题！

**Comment by youseries** [comment]
检查一下应该是hibernate方言配置问题
