### ISSUE TITLE
数据库兼容性问题

### ISSUE THREAD

**Issue by naonao123** [youseries/uflo#34]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UFlo的具体版本号：
<dependency>
            <groupId>com.bstek.uflo</groupId>
            <artifactId>uflo-console</artifactId>
            <version>2.1.1</version>
        </dependency>

*  #### 遇到的问题详细描述：

数据库兼容性问题：

数据库版本对 datatime 类型的字段支持不一致，导致如果程序中出现类似如下 new Date() 写法就会报错出现异常， 例如：
ProcessDefinition process = new ProcessDefinition();
process.setCreateDate(new Date());
session.save(process) ；

亲测数据库版本 mysql-5.7.20 。

问题修正实例：
SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
ProcessDefinition process = new ProcessDefinition();
process.setCreateDate(sdf.parse("2018-01-09 11:12:13"));
session.save(process) ；

注意日期格式："yyyy-MM-dd HH:mm:ss" 很重要，保证数据库的兼容性！

*  #### 涉及到的异常信息（完整异常信息）：
Caused by: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect datetime value: '' for column 'CREATE_DATE_' at row 1 at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2868) at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1573) at com.mysql.jdbc.ServerPreparedStatement.serverExecute(ServerPreparedStatement.java:1160) at com.mysql.jdbc.ServerPreparedStatement.executeInternal(ServerPreparedStatement.java:685) at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1400) at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1314) at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1299) at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105) at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105) at org.hibernate.id.IdentityGenerator$GetGeneratedKeysDelegate.executeAndExtract(IdentityGenerator.java:94) at org.hibernate.id.insert.AbstractReturningDelegate.performInsert(AbstractReturningDelegate.java:57) ... 109 more

*  #### 相关截图：
暂无

**Comment by youseries** [comment]
我觉得是你mysql驱动问题，你可以换个驱动版本试试，不可能是兼容性问题。

**Comment by naonao123** [comment]
非常感谢你的回复，@youseries 。
我还是觉得我们应该在自己的代码里面把这个问题给规避掉，不应该抛给第三方，也或者在详细说明里面告知一下用户，当然了这个只是个人观点。
目前正在读uflo的原代码，发现了很多在java 里面 new Date() 的场景，试想是否可以把这种 new Date() 的操作交给数据库的 时间来维护，例如在插入的时候交给mysql 的 now() 函数来完成 这样的问题应该就彻底的没有了。
