### ISSUE TITLE
spring boot 2.0集成uflo  hibernate报错

### ISSUE THREAD

**Issue by mickeyz** [youseries/uflo#68]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UFlo的具体版本号：
2.1.3

*  #### 遇到的问题详细描述：
spring boot 2.0集成uflo  hibernate报错   我试过spring boot 1.5.14没有报错 ，但是目前工程使用的是spring boot 2.0

*  #### 涉及到的异常信息（完整异常信息）：
Hibernate: select this_.ID_ as ID_1_7_0_, this_.BUSINESS_ID_ as BUSINESS2_7_0_, this_.CREATE_DATE_ as CREATE_D3_7_0_, this_.END_DATE_ as END_DATE4_7_0_, this_.PROCESS_ID_ as PROCESS_5_7_0_, this_.PROCESS_INSTANCE_ID_ as PROCESS_6_7_0_, this_.PROMOTER_ as PROMOTER7_7_0_, this_.SUBJECT_ as SUBJECT_8_7_0_, this_.TAG_ as TAG_9_7_0_ from UFLO_HIS_PROCESS_INSTANCE this_ where this_.END_DATE_ is not null and this_.PROCESS_ID_=? order by this_.CREATE_DATE_ desc limit ?
Hibernate: select processdef0_.ID_ as ID_1_11_0_, processdef0_.CATEGORY_ID_ as CATEGORY2_11_0_, processdef0_.CREATE_DATE_ as CREATE_D3_11_0_, processdef0_.DESCRIPTION_ as DESCRIPT4_11_0_, processdef0_.EFFECT_DATE_ as EFFECT_D5_11_0_, processdef0_.KEY_ as KEY_6_11_0_, processdef0_.NAME_ as NAME_7_11_0_, processdef0_.START_PROCESS_URL_ as START_PR8_11_0_, processdef0_.VERSION_ as VERSION_9_11_0_ from UFLO_PROCESS processdef0_ where processdef0_.ID_=?
2018-07-20 15:08:14,282 [http-nio-8080-exec-3] ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[ufloServlet] - Servlet.service() for servlet [ufloServlet] in context with path [] threw exception [javax.servlet.ServletException: java.lang.reflect.InvocationTargetException] with root cause
java.lang.NoSuchMethodError: org.hibernate.Session.createQuery(Ljava/lang/String;)Lorg/hibernate/Query;
	at com.bstek.uflo.command.impl.GetProcessCommand.parseProcess(GetProcessCommand.java:89)
	at com.bstek.uflo.command.impl.GetProcessCommand.execute(GetProcessCommand.java:54)
	at com.bstek.uflo.command.impl.GetProcessCommand.execute(GetProcessCommand.java:38)
	at com.bstek.uflo.command.impl.SpringTransactionCommandService$1.doInTransaction(SpringTransactionCommandService.java:53)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)
	at com.bstek.uflo.command.impl.SpringTransactionCommandService.executeCommand(SpringTransactionCommandService.java:51)
	at com.bstek.uflo.service.impl.DefaultProcessService.getProcessById(DefaultProcessService.java:72)
	at com.bstek.uflo.service.impl.DefaultProcessService.startProcessById(DefaultProcessService.java:133)
	at com.bstek.uflo.console.handler.impl.central.CentralServletHandler.startProcess(CentralServletHandler.java:189)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.bstek.uflo.console.handler.BaseServletHandler.invokeMethod(BaseServletHandler.java:36)
	at com.bstek.uflo.console.handler.impl.central.CentralServletHandler.execute(CentralServletHandler.java:69)
	at com.bstek.uflo.console.UfloServlet.service(UfloServlet.java:82)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:61)
	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:387)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.alibaba.druid.support.http.WebStatFilter.doFilter(WebStatFilter.java:123)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:109)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:496)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1468)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)

*  #### 相关截图：

**Comment by mickeyz** [comment]
将hibernate  降到5.0.12问题解决
